### ISSUE TITLE
Unexpected pattern matching precedence

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddcast#26]
If you define a set of handlers like this:
```JS
	service.bus.queryHandler(
		{role: 'catalog', cmd: 'fetchItem'},
		queries.fetchItem
	);

	service.bus.queryHandler(
		{role: 'catalog', cmd: 'fetchItemList'},
		queries.fetchItemList
	);

	service.bus.queryHandler(
		{role: 'catalog', cmd: 'fetchItemSpec'},
		queries.fetchItemSpec
	);

	service.bus.queryHandler(
		{role: 'catalog', cmd: 'fetchItemSpecList'},
		queries.fetchItemSpecList
	);
```

Then 'fetchItemList' , 'fetchItemSpec', and 'fetchItemSpecList' will never match because 'fetchItem' will always take precedence.

This is an unexpected behavior, and makes it really difficult for a programmer to be aware of and mitigate.

**Comment by blainsmith** [comment]
Noting this here since It might be worth using now. https://github.com/mcollina/bloomrun
